//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbGenLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcControllerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcControllerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbGenLibrary.Properties.MvcControllerResources", typeof(MvcControllerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Linq;
        ///using System.Net;
        ///using System.Web.Mvc;
        ///using @MvcNameSpace@.Models;
        ///using @NameSpace@.Mapping;
        ///using @NameSpace@.Services;
        ///using PagedList;
        ///
        ///namespace @MvcNameSpace@.Controllers
        ///{
        ///    public class @ClassName@Controller : Controller
        ///    {
        ///        private readonly @ClassName@Service _db = new @ClassName@Service();
        ///
        ///        public ActionResult Index(int? page)
        ///        {
        ///            var @ClassNameLower@ = _db.GetAll().Select(e =&gt; (@ClassName@Model)e).ToList();
        ///            re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public ActionResult Delete(@KeyType?@ id, int? page)
        ///        {
        ///            if (id == null)
        ///            {
        ///                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ///            }
        ///            @ClassName@Model @ClassNameLower@ = _db.Find(e =&gt; e.@PrimaryKey@ == @KeyVal@).FirstOrDefault();
        ///            
        ///            if (@ClassNameLower@ == null)
        ///            {
        ///                return HttpNotFound();
        ///            }
        ///            _db.Delete(@ClassNameLower@);
        ///            return RedirectToAct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public ActionResult Details(@KeyType?@ id)
        ///        {
        ///            if (id == null)
        ///            {
        ///                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ///            }
        ///            @ClassName@Model @ClassNameLower@ = _db.Find(e=&gt;e.@PrimaryKey@==@KeyVal@).FirstOrDefault();
        ///            if (@ClassNameLower@ == null)
        ///            {
        ///                return HttpNotFound();
        ///            }
        ///            return View(@ClassNameLower@);
        ///        }.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public ActionResult Edit(@KeyType?@ id)
        ///        {
        ///            if (id == null)
        ///            {
        ///                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ///            }
        ///            @ClassName@Model @ClassNameLower@ = _db.Find(e =&gt; e.@PrimaryKey@ == @KeyVal@).FirstOrDefault();
        ///            if (@ClassNameLower@ == null)
        ///            {
        ///                return HttpNotFound();
        ///            }
        ///            return View(@ClassNameLower@);
        ///        }
        ///
        ///        [HttpPost]
        ///        public ActionResu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
    }
}
