//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbGenLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcViewsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcViewsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbGenLibrary.Properties.MvcViewsResources", typeof(MvcViewsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;form-group&quot;&gt;
        ///            @Html.LabelFor(model =&gt; model.@ColumnName@, new { @class = &quot;control-label col-md-2&quot; })
        ///            &lt;div class=&quot;col-md-10&quot;&gt;
        ///                @Html.EditorFor(model =&gt; model.@ColumnName@, new { htmlAttributes = new { @class = &quot;form-control&quot; } })
        ///                @Html.ValidationMessageFor(model =&gt; model.@ColumnName@, &quot;&quot;, new { @class = &quot;text-danger&quot; })
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string Create_RenderColums {
            get {
                return ResourceManager.GetString("Create_RenderColums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model @MvcNameSpace@.Models.@ClassName@Model
        ///
        ///@{
        ///    ViewBag.Title = &quot;Tạo mới &quot;;
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///
        ///&lt;h2&gt;Tạo mới @Html.LabelForModel()&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///
        ///@using (Html.BeginForm())
        ///{
        ///    &lt;div class=&quot;form-horizontal&quot;&gt;
        ///        &lt;h4&gt;@Html.LabelForModel()&lt;/h4&gt;
        ///        &lt;hr /&gt;
        ///        @Html.ValidationSummary(true, &quot;&quot;, new { @class = &quot;text-danger&quot; })
        ///
        ///@RenderColums@
        ///
        ///
        ///        &lt;div class=&quot;form-group&quot;&gt;
        ///            &lt;div class=&quot;col-md-offset-2 col-md-10&quot;&gt;
        ///                &lt;in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Createcshtml {
            get {
                return ResourceManager.GetString("Createcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dt&gt;
        ///            @Html.DisplayNameFor(model =&gt; model.@ColumnName@)
        ///        &lt;/dt&gt;
        ///
        ///        &lt;dd&gt;
        ///            @Html.DisplayFor(model =&gt; model.@ColumnName@)
        ///        &lt;/dd&gt;.
        /// </summary>
        internal static string Details_RenderColums {
            get {
                return ResourceManager.GetString("Details_RenderColums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model @MvcNameSpace@.Models.@ClassName@Model
        ///
        ///@{
        ///    ViewBag.Title = &quot;Chi Tiết &quot;+@Html.LabelForModel();
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///
        ///&lt;h2&gt;Hiển thị chi tiết @Html.LabelForModel()&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///&lt;div&gt;
        ///    &lt;h4&gt;@Html.LabelForModel()&lt;/h4&gt;
        ///    &lt;hr /&gt;
        ///    &lt;dl class=&quot;dl-horizontal&quot;&gt;
        ///
        ///@RenderColums@
        ///
        ///		
        ///    &lt;/dl&gt;
        ///&lt;/div&gt;
        ///&lt;p&gt;
        ///    @Html.ActionLink(&quot;Chỉnh sửa&quot;, &quot;Edit&quot;, new { id = Model.EmployeeID }) |
        ///    @Html.ActionLink(&quot;Trở về trang chủ&quot;, &quot;Index&quot;)
        ///&lt;/p&gt;
        ///.
        /// </summary>
        internal static string Detailscshtml {
            get {
                return ResourceManager.GetString("Detailscshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;form-group&quot;&gt;
        ///            @Html.LabelFor(model =&gt; model.@ColumnName@, new {@class = &quot;control-label col-md-2&quot;})
        ///            &lt;div class=&quot;col-md-10&quot;&gt;
        ///                @Html.EditorFor(model =&gt; model.@ColumnName@, new {htmlAttributes = new {@class = &quot;form-control&quot;}})
        ///                @Html.ValidationMessageFor(model =&gt; model.@ColumnName@, &quot;&quot;, new {@class = &quot;text-danger&quot;})
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        internal static string Edit_RenderColums {
            get {
                return ResourceManager.GetString("Edit_RenderColums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model @MvcNameSpace@.Models.@ClassName@Model
        ///
        ///@{
        ///    ViewBag.Title = &quot;Chỉnh sửa &quot;;
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///
        ///&lt;h2&gt;Chỉnh sửa @Html.LabelForModel()&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///
        ///@using (Html.BeginForm())
        ///{
        ///    &lt;div class=&quot;form-horizontal&quot;&gt;
        ///        &lt;h4&gt;@Html.LabelForModel()&lt;/h4&gt;
        ///        &lt;hr /&gt;
        ///        @Html.ValidationSummary(true, &quot;&quot;, new {@class = &quot;text-danger&quot;})
        ///        @Html.HiddenFor(model =&gt; model.@PrimaryKey@)
        ///
        ///		
        ///@RenderColums@
        ///
        ///
        ///        &lt;div class=&quot;form-group&quot;&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Editcshtml {
            get {
                return ResourceManager.GetString("Editcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///@{
        ///    ViewBag.Title = &quot;Index&quot;;
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///
        ///&lt;h2&gt;@WebTitle@&lt;/h2&gt;
        ///&lt;hr/&gt;
        ///
        ///
        ///&lt;h4&gt;Các chức năng chính&lt;/h4&gt;
        ///&lt;ol&gt;
        ///
        ///@ActionLink@
        ///
        ///&lt;/ol&gt;
        ///
        ///.
        /// </summary>
        internal static string HomeIndexcshtml {
            get {
                return ResourceManager.GetString("HomeIndexcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ActionLink(&quot; &quot;, &quot;Edit&quot;, new { id = item.@PrimaryKey@ }, new { @class = &quot;glyphicon glyphicon-pencil text-warning&quot; }) |
        ///                @Html.ActionLink(&quot; &quot;, &quot;Details&quot;, new { id = item.@PrimaryKey@ }, new { @class = &quot;glyphicon glyphicon-eye-open text-success&quot; })|
        ///                @Html.ActionLink(&quot; &quot;, &quot;Delete&quot;, new { id = item.@PrimaryKey@, page = Model.PageNumber }, new { @class = &quot;glyphicon glyphicon-remove text-danger&quot;, onclick = &quot;return confirm(&apos;Bạn có muốn xóa dòng này?&apos;)&quot; }).
        /// </summary>
        internal static string Index_RenderActions {
            get {
                return ResourceManager.GetString("Index_RenderActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///                @Html.DisplayFor(modelItem =&gt; item.@ColumnName@)
        ///            &lt;/td&gt;.
        /// </summary>
        internal static string Index_RenderColumsDisplay {
            get {
                return ResourceManager.GetString("Index_RenderColumsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;
        ///            @Html.DisplayNameFor(model =&gt; model.First().@ColumnName@)
        ///        &lt;/th&gt;.
        /// </summary>
        internal static string Index_RenderColumsDisplayName {
            get {
                return ResourceManager.GetString("Index_RenderColumsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using @MvcNameSpace@.Models
        ///@using PagedList.Mvc
        ///@model PagedList.IPagedList&lt;@ClassName@Model&gt;
        ///
        ///@{
        ///    ViewBag.Title = &quot;Trang chủ &quot;;
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///
        ///&lt;h2&gt;Trang chủ&lt;/h2&gt;
        ///&lt;hr /&gt;
        ///&lt;p&gt;
        ///    @Html.ActionLink(&quot;Tạo mới&quot;, &quot;Create&quot;)
        ///&lt;/p&gt;
        ///&lt;table class=&quot;table table-bordered table-hover table-striped&quot;&gt;
        ///    &lt;tr&gt;
        ///
        ///@RenderColumsDisplayName@	
        ///
        ///
        ///
        ///        &lt;th&gt;&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///
        ///    @foreach (@ClassName@Model item in Model)
        ///    {
        ///        &lt;tr&gt;
        ///
        ///@RenderColumsDisplay@	
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Indexcshtml {
            get {
                return ResourceManager.GetString("Indexcshtml", resourceCulture);
            }
        }
    }
}
