//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbGenLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbGenLibrary.Properties.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;@ViewBag.Title - My ASP.NET Application&lt;/title&gt;
        ///    @Styles.Render(&quot;~/Content/css&quot;)
        ///    @Scripts.Render(&quot;~/bundles/modernizr&quot;)
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;navbar navbar-inverse navbar-fixed-top&quot;&gt;
        ///        &lt;div class=&quot;container&quot;&gt;
        ///            &lt;div class=&quot;navbar-header&quot;&gt;
        ///                @Html.ActionLink(&quot;Trang chủ&quot;, &quot;Index&quot;, &quot;Home&quot;, new { area = &quot;&quot; }, n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Layoutcshtml {
            get {
                return ResourceManager.GetString("_Layoutcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}
        ///.
        /// </summary>
        internal static string _ViewStartcshtml {
            get {
                return ResourceManager.GetString("_ViewStartcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// General Information about an assembly is controlled through the following
        ///// set of attributes. Change these attribute values to modify the information
        ///// associated with an assembly.
        ///[assembly: AssemblyTitle(&quot;@MvcNameSpace@&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;&quot;)]
        ///[assembly: AssemblyProduct(&quot;@MvcNameSpace@&quot;)]
        ///[assembly: Ass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyInfo {
            get {
                return ResourceManager.GetString("AssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. Ins [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrapjs {
            get {
                return ResourceManager.GetString("bootstrapjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Web;
        ///using System.Web.Optimization;
        ///
        ///namespace @MvcNameSpace@
        ///{
        ///    public class BundleConfig
        ///    {
        ///        // For more information on bundling, visit http://go.microsoft.com/fwlink/?LinkId=301862
        ///        public static void RegisterBundles(BundleCollection bundles)
        ///        {
        ///            bundles.Add(new ScriptBundle(&quot;~/bundles/jquery&quot;).Include(
        ///                        &quot;~/Scripts/jquery-{version}.js&quot;));
        ///
        ///            bundles.Add(new ScriptBundle(&quot;~/bundles/jqueryval&quot;).Include(
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BundleConfig {
            get {
                return ResourceManager.GetString("BundleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    Layout = null;
        ///}
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;title&gt;Lỗi&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;hgroup&gt;
        ///        &lt;h1&gt;Opps.&lt;/h1&gt;
        ///        &lt;h2&gt;Xin lỗi, đã có lỗi xảy ra trong quá trình xử lý yêu cầu của bạn. Xin lỗi vì sự bất tiện này!&lt;/h2&gt;
        ///    &lt;/hgroup&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string Errorcshtml {
            get {
                return ResourceManager.GetString("Errorcshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Web;
        ///using System.Web.Mvc;
        ///
        ///namespace @MvcNameSpace@
        ///{
        ///    public class FilterConfig
        ///    {
        ///        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        ///        {
        ///            filters.Add(new HandleErrorAttribute());
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string FilterConfig {
            get {
                return ResourceManager.GetString("FilterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Application Codebehind=&quot;Global.asax.cs&quot; Inherits=&quot;@MvcNameSpace@.MvcApplication&quot; Language=&quot;C#&quot; %&gt;
        ///.
        /// </summary>
        internal static string Globalasax {
            get {
                return ResourceManager.GetString("Globalasax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using System.Web.Optimization;
        ///using System.Web.Routing;
        ///
        ///namespace @MvcNameSpace@
        ///{
        ///    public class MvcApplication : HttpApplication
        ///    {
        ///        static MvcApplication()
        ///        {
        ///            
        ///        }
        ///
        ///        protected void Application_Start()
        ///        {
        ///            AreaRegistration.RegisterAllAreas();
        ///            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Globalasaxcs {
            get {
                return ResourceManager.GetString("Globalasaxcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regulareot {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regulareot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regularsvg {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regularsvg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regularttf {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regularttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] glyphicons_halflings_regularwoff {
            get {
                object obj = ResourceManager.GetObject("glyphicons_halflings_regularwoff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///
        ///namespace @MvcNameSpace@.Controllers
        ///{
        ///    public class HomeController : Controller
        ///    {
        ///        public ActionResult Index()
        ///        {
        ///            return View();
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string HomeController {
            get {
                return ResourceManager.GetString("HomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v2.1.1
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2014-05-01T17:11Z
        /// */
        ///
        ///(function( global, factory ) {
        ///
        ///	if ( typeof module === &quot;object&quot; &amp;&amp; typeof module.exports === &quot;object&quot; ) {
        ///		// For CommonJS and CommonJS-like environments where a proper window is present,
        ///		// execute the factory and get jQuery [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_211 {
            get {
                return ResourceManager.GetString("jquery_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intellisense.annotate(jQuery, {
        ///  &apos;ajax&apos;: function() {
        ///    /// &lt;signature&gt;
        ///    ///   &lt;summary&gt;Perform an asynchronous HTTP (Ajax) request.&lt;/summary&gt;
        ///    ///   &lt;param name=&quot;url&quot; type=&quot;String&quot;&gt;A string containing the URL to which the request is sent.&lt;/param&gt;
        ///    ///   &lt;param name=&quot;settings&quot; type=&quot;PlainObject&quot;&gt;A set of key/value pairs that configure the Ajax request. All settings are optional. A default can be set for any option with $.ajaxSetup(). See jQuery.ajax( settings ) below for a complete list of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_211intellisense {
            get {
                return ResourceManager.GetString("jquery_211intellisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;file&quot;:&quot;jquery-2.1.1.min.js&quot;,&quot;sources&quot;:[&quot;jquery-2.1.1.js&quot;],&quot;names&quot;:[&quot;global&quot;,&quot;factory&quot;,&quot;module&quot;,&quot;exports&quot;,&quot;document&quot;,&quot;w&quot;,&quot;Error&quot;,&quot;window&quot;,&quot;this&quot;,&quot;noGlobal&quot;,&quot;arr&quot;,&quot;slice&quot;,&quot;concat&quot;,&quot;push&quot;,&quot;indexOf&quot;,&quot;class2type&quot;,&quot;toString&quot;,&quot;hasOwn&quot;,&quot;hasOwnProperty&quot;,&quot;support&quot;,&quot;version&quot;,&quot;jQuery&quot;,&quot;selector&quot;,&quot;context&quot;,&quot;fn&quot;,&quot;init&quot;,&quot;rtrim&quot;,&quot;rmsPrefix&quot;,&quot;rdashAlpha&quot;,&quot;fcamelCase&quot;,&quot;all&quot;,&quot;letter&quot;,&quot;toUpperCase&quot;,&quot;prototype&quot;,&quot;jquery&quot;,&quot;constructor&quot;,&quot;length&quot;,&quot;toArray&quot;,&quot;call&quot;,&quot;get&quot;,&quot;num&quot;,&quot;pushStack&quot;,&quot;elems&quot;,&quot;ret&quot;,&quot;merge&quot;,&quot;pr....
        /// </summary>
        internal static string jquery_211minmap {
            get {
                return ResourceManager.GetString("jquery_211minmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery Validation Plugin - v1.11.0 - 2/4/2013
        ///* https://github.com/jzaefferer/jquery-validation
        ///* Copyright (c) 2013 Jörn Zaefferer; Licensed MIT */
        ///
        ///(function($) {
        ///
        ///$.extend($.fn, {
        ///	// http://docs.jquery.com/Plugins/Validation/validate
        ///	validate: function( options ) {
        ///
        ///		// if nothing is selected, return nothing; can&apos;t chain anyway
        ///		if ( !this.length ) {
        ///			if ( options &amp;&amp; options.debug &amp;&amp; window.console ) {
        ///				console.warn( &quot;Nothing selected, can&apos;t validate, returning nothing.&quot; );
        ///			}
        ///			return;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryvalidate {
            get {
                return ResourceManager.GetString("jqueryvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* This file has been commented to support Visual Studio Intellisense.
        ///* You should not use this file at runtime inside the browser--it is only
        ///* intended to be used only for design-time IntelliSense.  Please use the
        ///* standard jQuery library for all production use.
        ///*
        ///* Comment version: 1.11.0
        ///*/
        ///
        ////*
        ///* Note: While Microsoft is not the author of this file, Microsoft is
        ///* offering you a license subject to the terms of the Microsoft Software
        ///* License Terms for Microsoft ASP.NET Model View Contro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryvalidate_vsdoc {
            get {
                return ResourceManager.GetString("jqueryvalidate_vsdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryvalidateunobtrusive {
            get {
                return ResourceManager.GetString("jqueryvalidateunobtrusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;packages&gt;
        ///  &lt;package id=&quot;Antlr&quot; version=&quot;3.4.1.9004&quot; targetFramework=&quot;net451&quot; /&gt;
        ///  &lt;package id=&quot;BLToolkit&quot; version=&quot;4.1.21&quot; targetFramework=&quot;net451&quot; /&gt;
        ///  &lt;package id=&quot;bootstrap&quot; version=&quot;3.0.0&quot; targetFramework=&quot;net451&quot; /&gt;
        ///  &lt;package id=&quot;jQuery&quot; version=&quot;2.1.1&quot; targetFramework=&quot;net451&quot; /&gt;
        ///  &lt;package id=&quot;jQuery.Validation&quot; version=&quot;1.11.0&quot; targetFramework=&quot;net451&quot; /&gt;
        ///  &lt;package id=&quot;jQuery.Validation.Unobtrusive.Native.MVC5&quot; version=&quot;1.1.1.0&quot; targetFramework=&quot;net4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string packagesMVC {
            get {
                return ResourceManager.GetString("packagesMVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///
        ///namespace @MvcNameSpace@
        ///{
        ///    public class PageConfig
        ///    {
        ///        private static int _pageSize = @PageSize@;
        ///
        ///        public static int PageSize
        ///        {
        ///            get { return _pageSize &gt; 0 ? _pageSize : 20; }
        ///            set { _pageSize = value; }
        ///        }
        ///
        ///        static PageConfig()
        ///        {
        ///
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string PageConfig {
            get {
                return ResourceManager.GetString("PageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pagination {
        ///  display: inline-block;
        ///  padding-left: 0;
        ///  margin: 20px 0;
        ///  border-radius: 4px;
        ///}
        ///
        ///.pagination &gt; li {
        ///  display: inline;
        ///}
        ///
        ///.pagination &gt; li &gt; a,
        ///.pagination &gt; li &gt; span {
        ///  position: relative;
        ///  float: left;
        ///  padding: 6px 12px;
        ///  margin-left: -1px;
        ///  line-height: 1.428571429;
        ///  text-decoration: none;
        ///  background-color: #ffffff;
        ///  border: 1px solid #dddddd;
        ///}
        ///
        ///.pagination &gt; li:first-child &gt; a,
        ///.pagination &gt; li:first-child &gt; span {
        ///  margin-left: 0;
        ///  border-bottom-left-radius: 4px;
        ///  bor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PagedList {
            get {
                return ResourceManager.GetString("PagedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Projectcsproj {
            get {
                return ResourceManager.GetString("Projectcsproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;autosync enabled=&quot;true&quot; /&gt;
        ////// &lt;reference path=&quot;bootstrap.js&quot; /&gt;
        ////// &lt;reference path=&quot;jquery-2.1.1.js&quot; /&gt;
        ////// &lt;reference path=&quot;jquery.validate.js&quot; /&gt;
        ////// &lt;reference path=&quot;jquery.validate.unobtrusive.js&quot; /&gt;
        ////// &lt;reference path=&quot;respond.js&quot; /&gt;
        ///.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;repositories&gt;
        ///  &lt;repository path=&quot;..\@MvcNameSpace@\packages.config&quot; /&gt;
        ///  &lt;repository path=&quot;..\@NameSpace@\packages.config&quot; /&gt;
        ///&lt;/repositories&gt;.
        /// </summary>
        internal static string repositories {
            get {
                return ResourceManager.GetString("repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* NUGET: BEGIN LICENSE TEXT
        /// *
        /// * Microsoft grants you the right to use these script files for the sole
        /// * purpose of either: (i) interacting through your browser with the Microsoft
        /// * website or online service, subject to the applicable licensing or use
        /// * terms; or (ii) using the files as included with a Microsoft product subject
        /// * to that product&apos;s license terms. Microsoft reserves all other rights to the
        /// * files not expressly granted by Microsoft, whether by implication, estoppel
        /// * or otherwise. Ins [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string respond {
            get {
                return ResourceManager.GetString("respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using System.Web.Routing;
        ///
        ///namespace @MvcNameSpace@
        ///{
        ///    public class RouteConfig
        ///    {
        ///        public static void RegisterRoutes(RouteCollection routes)
        ///        {
        ///            routes.IgnoreRoute(&quot;{resource}.axd/{*pathInfo}&quot;);
        ///
        ///            routes.MapRoute(&quot;Default&quot;, &quot;{controller}/{action}/{id}&quot;, new { controller = &quot;Home&quot;, action = &quot;Index&quot;, id = UrlParameter.Optional }
        ///            );
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RouteConfig {
            get {
                return ResourceManager.GetString("RouteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    padding-top: 50px;
        ///    padding-bottom: 20px;
        ///}
        ///
        ///.body-content {
        ///    padding-left: 15px;
        ///    padding-right: 15px;
        ///}
        ///
        ///input,
        ///select,
        ///textarea {
        ///    max-width: 280px;
        ///}
        ///
        ///.pagination-container {
        ///    text-align: center;
        ///}
        ///.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.30324.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;@MvcNameSpace@&quot;, &quot;@MvcNameSpace@\@MvcNameSpace@.csproj&quot;, &quot;{39EDFA9F-CAEC-46DB-A961-B483C53EBF0E}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;@NameSpace@&quot;, &quot;@NameSpace@\@NameSpace@.csproj&quot;, &quot;{0552B26A-25D3-41E0-93DE-C03AA528F17B}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(Soluti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Solutionsln {
            get {
                return ResourceManager.GetString("Solutionsln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///  For more information on how to configure your ASP.NET application, please visit
        ///  http://go.microsoft.com/fwlink/?LinkId=301880
        ///  --&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;webpages:Version&quot; value=&quot;3.0.0.0&quot; /&gt;
        ///    &lt;add key=&quot;webpages:Enabled&quot; value=&quot;false&quot; /&gt;
        ///    &lt;add key=&quot;ClientValidationEnabled&quot; value=&quot;true&quot; /&gt;
        ///    &lt;add key=&quot;UnobtrusiveJavaScriptEnabled&quot; value=&quot;true&quot; /&gt;
        ///  &lt;/appSettings&gt;
        ///  &lt;system.web&gt;
        ///    &lt;compilation debug=&quot;true&quot; targetFram [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;sectionGroup name=&quot;system.web.webPages.razor&quot; type=&quot;System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot;&gt;
        ///      &lt;section name=&quot;host&quot; type=&quot;System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot; requirePermission=&quot;false&quot; /&gt;
        ///      &lt;section name=&quot;page [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Webconfig_View {
            get {
                return ResourceManager.GetString("Webconfig_View", resourceCulture);
            }
        }
    }
}
